process announce-routes {
    run /usr/bin/python3 /opt/exabgp/announcer.py;
    encoder json;
}

neighbor 10.0.44.1 {
    router-id 10.0.44.2;
    local-address 10.0.44.2;
    local-as 65040;
    peer-as 65030;

    family {
        ipv4 unicast;
    }

    api {
        processes [ announce-routes ];
        receive {
            parsed;
        }
    }
}
